
# zsh plugins installed with https://github.com/zsh-users/antigen
source /usr/local/share/antigen/antigen.zsh
antigen init {{salted}}/antigenrc

for filename in {{salted}}/settings/*.zsh; do
  source $filename
done
